# image will be published to ghcr.io/<user>/<name>
name: pancake

# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-modules.yml

  - type: dnf
    repos:
      copr:
        - sneexy/python-validity

    install:
      packages:
        - open-fprintd
        - fprintd-clients
        - fprintd-clients-pam
        - python3-validity
    
    remove:
      auto-remove: false
      packages:
        - fprintd
        - fprintd-pam
    
  - type: script
    scripts:
      - python-validity.sh